records:
- role: programmer
  metric: weekly_delivery_count
  value: 1.0
  date: '2026-07-04'
  recorded_at: '2026-07-04T23:53:49'
- role: product_manager
  metric: weekly_topics
  value: 1.0
  date: '2026-07-04'
  recorded_at: '2026-07-04T23:53:55'
