paypal_client_id: ref://.secrets/secrets.json#paypal_client_id
paypal_client_secret: ref://.secrets/secrets.json#paypal_client_secret
test_api_key: ref://.secrets/secrets.json#test_api_key
wallet_ethereum_c0f3789c_priv: ref://.secrets/secrets.json#wallet_ethereum_c0f3789c_priv
