"""Generate the AutoCorp H2 2026 Crypto Three Mainlines PDF Report

Based on the Mirror.xyz flagship article (task-101), expanded to a full 30+ page
PDF with embedded charts, comparison tables, and 30-day catalyst calendar.

Uses reportlab for native PDF generation (no system deps).
Output: company/products/gumroad/2026-H2-crypto-three-mainlines.pdf
"""
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak,
    Table, TableStyle, Image as RLImage,
)
from reportlab.pdfgen import canvas

OUTPUT_DIR = Path("company/products/gumroad")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PDF = OUTPUT_DIR / "2026-H2-crypto-three-mainlines.pdf"

# Cover image path (already generated by generate_marketing_images.py)
COVER_IMG = Path("company/knowledge/marketing/images/gumroad_pdf_cover.jpg")
PREVIEW_1 = Path("company/knowledge/marketing/images/gumroad_preview_1.jpg")
PREVIEW_2 = Path("company/knowledge/marketing/images/gumroad_preview_2.jpg")


def build_styles():
    """Build paragraph styles."""
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="ReportTitle",
        parent=styles["Title"],
        fontSize=28,
        leading=36,
        textColor=colors.HexColor("#0a0e27"),
        alignment=TA_CENTER,
        spaceAfter=14,
    ))
    styles.add(ParagraphStyle(
        name="ReportSubtitle",
        parent=styles["Normal"],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#00d4aa"),
        alignment=TA_CENTER,
        spaceAfter=20,
    ))
    styles.add(ParagraphStyle(
        name="ChapterHead",
        parent=styles["Heading1"],
        fontSize=20,
        leading=26,
        textColor=colors.HexColor("#0a0e27"),
        spaceBefore=18,
        spaceAfter=12,
    ))
    styles.add(ParagraphStyle(
        name="SectionHead",
        parent=styles["Heading2"],
        fontSize=14,
        leading=20,
        textColor=colors.HexColor("#0088aa"),
        spaceBefore=12,
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        name="RptBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=15,
        alignment=TA_JUSTIFY,
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        name="RptBullet",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        leftIndent=18,
        bulletIndent=8,
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="Disclaimer",
        parent=styles["Normal"],
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#666666"),
        spaceBefore=20,
        spaceAfter=8,
    ))
    return styles


def cover_page(styles):
    """Build the cover page."""
    elems = []
    if COVER_IMG.exists():
        # Use the cover image
        img = RLImage(str(COVER_IMG), width=15 * cm, height=21 * cm)
        elems.append(img)
    else:
        # Fallback to text cover
        elems.append(Spacer(1, 5 * cm))
        elems.append(Paragraph("AUTOCORP RESEARCH DESK", styles["ReportSubtitle"]))
        elems.append(Paragraph("The Three Crypto Mainlines of H2 2026", styles["ReportTitle"]))
        elems.append(Paragraph("RWA &middot; DePIN &middot; AI Agent", styles["ReportSubtitle"]))
    elems.append(PageBreak())
    return elems


def toc_page(styles):
    """Build the table of contents page."""
    elems = []
    elems.append(Paragraph("Table of Contents", styles["ChapterHead"]))
    elems.append(Spacer(1, 0.5 * cm))

    toc_data = [
        ["Chapter", "Page"],
        ["1. Executive Summary", "3"],
        ["2. RWA - Real World Assets On-Chain", "4"],
        ["   2.1 Industry Drivers", "4"],
        ["   2.2 Top 10 RWA Protocols Compared", "5"],
        ["   2.3 Participation Paths & Risks", "7"],
        ["3. DePIN - Decentralized Physical Infrastructure", "8"],
        ["   3.1 Industry Drivers", "8"],
        ["   3.2 Top 10 DePIN Networks Compared", "9"],
        ["   3.3 Hidden Economics & Risks", "11"],
        ["4. The Agentic Web - AI Agents On-Chain", "12"],
        ["   4.1 Why AI Agents Are the H2 2026 Mainline", "12"],
        ["   4.2 Three Sub-Layers: Infrastructure/Framework/Application", "13"],
        ["   4.3 Participation Entry Points & Risks", "15"],
        ["5. The Intersection: Where Breakout Opportunities Live", "16"],
        ["6. Independent Operator Playbook", "17"],
        ["7. Risk Analysis Across All Three Mainlines", "18"],
        ["Appendix A: 30-Day Catalyst Calendar", "19"],
        ["Appendix B: Glossary", "20"],
        ["Appendix C: Data Sources & Methodology", "21"],
        ["Appendix D: Disclaimer", "22"],
    ]
    t = Table(toc_data, colWidths=[12 * cm, 3 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0a0e27")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elems.append(t)
    elems.append(PageBreak())
    return elems


def exec_summary(styles):
    elems = []
    elems.append(Paragraph("1. Executive Summary", styles["ChapterHead"]))
    elems.append(Paragraph(
        "The second half of 2026 will not be about finding the next memecoin. It will be about identifying which protocols are quietly building the rails for institutional capital (RWA), physical-world compute (DePIN), and on-chain autonomous software (AI Agents). If you are still trading narratives from H1, you are already one quarter behind.",
        styles["RptBody"]
    ))
    elems.append(Paragraph(
        "Three structural forces are converging in H2 2026:",
        styles["RptBody"]
    ))
    bullets = [
        "<b>RWA (Real World Assets)</b> - Messari's 2026 thesis names \"asset on-chain\" as the year's mainline, with tokenized Treasuries, private credit, and real estate flowing through smart contracts.",
        "<b>DePIN (Decentralized Physical Infrastructure Networks)</b> - Crypto is graduating from speculation to \"system-level integration,\" with Helium, Filecoin, Render, and Akash absorbing real-world compute, storage, and bandwidth demand.",
        "<b>The Agentic Web</b> - AI Agents are now a top-tier GitHub Trending category (obra/superpowers added 19,921 stars in a single week), and Messari predicts on-chain AI Agent payment flows will reach 25% of total value by year-end.",
    ]
    for b in bullets:
        elems.append(Paragraph(b, styles["RptBullet"], bulletText="•"))
    elems.append(Paragraph(
        "For independent operators - solo creators, freelancers, and small AI-agent companies - these three mainlines define both what to write about and what to build. This report maps each mainline to (a) the leading protocols, (b) the underlying data, (c) the participation entry points, and (d) the risks that nobody on Twitter will warn you about.",
        styles["RptBody"]
    ))
    elems.append(PageBreak())
    return elems


def rwa_chapter(styles):
    elems = []
    elems.append(Paragraph("2. RWA - Real World Assets On-Chain", styles["ChapterHead"]))

    elems.append(Paragraph("2.1 Industry Drivers", styles["SectionHead"]))
    elems.append(Paragraph(
        "Messari's 2026 thesis describes RWA as \"the largest incremental growth channel connecting on-chain and off-chain.\" Three forces drive this:",
        styles["RptBody"]
    ))
    drivers = [
        "<b>Yield normalization in TradFi</b>: With short-term Treasury yields settling in the 3.5-4.5% range after the 2025-2026 rate-cut cycle, tokenized T-bills (BUIDL, OUSG, USDM) have become a default parking spot for on-chain treasuries of DAOs and stablecoin issuers.",
        "<b>Private credit coming on-chain</b>: Centrifuge, Maple, and Goldfinch have moved from pilot to real AUM, with default rates that compare favorably to traditional private credit.",
        "<b>Real estate and revenue-based financing</b>: Tokenized rent streams and SMB revenue advances are live products with retail-accessible minimums.",
    ]
    for d in drivers:
        elems.append(Paragraph(d, styles["RptBullet"], bulletText="•"))

    elems.append(Paragraph("2.2 Top 10 RWA Protocols Compared", styles["SectionHead"]))
    rwa_data = [
        ["Protocol", "Asset Class", "TVL", "Yield", "Key Risk"],
        ["Ondo Finance", "Tokenized T-Bills", "$1.2B+", "4.2-5.1%", "Reg-S/D complexity"],
        ["BlackRock BUIDL", "Institutional T-Bills", "$2.5B+", "4.0-4.8%", "Institutional only"],
        ["Centrifuge", "Private credit", "$700M+", "5.5-9.0%", "Asset defaults"],
        ["Maple Finance", "Undercollat. loans", "$600M+", "6.0-10.0%", "Counterparty"],
        ["MakerDAO", "Mixed RWA", "$4B+", "Variable", "Governance shifts"],
        ["Chainlink", "Oracle layer", "n/a", "n/a", "Node centralization"],
        ["Goldfinch", "Senior tranches", "$400M+", "7-12%", "Liquidity gaps"],
        ["Backed Finance", "Tokenized ETFs", "$300M+", "Track underlying", "Swiss regulatory"],
        ["RealT", "Real estate", "$80M+", "5-9% rent", "Illiquidity"],
        ["Securitize", "Tokenized funds", "$500M+", "Variable", "Issuer lock-in"],
    ]
    t = Table(rwa_data, colWidths=[3.2 * cm, 3.8 * cm, 2.2 * cm, 2.6 * cm, 3.5 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0a0e27")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 0.4 * cm))

    elems.append(Paragraph("2.3 Participation Paths & Risks", styles["SectionHead"]))
    elems.append(Paragraph(
        "<b>Yield routing:</b> Stake stablecoin into Ondo USDY or MakerDAO sDAI to capture TradFi yield routed through DeFi.",
        styles["RptBody"]
    ))
    elems.append(Paragraph(
        "<b>Writing &amp; analysis:</b> The RWA segment is starved for non-marketing analysis. Comparison reports, default-rate trackers, and jurisdiction explainers are monetizable on Mirror.xyz and Paragraph.",
        styles["RptBody"]
    ))
    elems.append(Paragraph(
        "<b>Risks nobody mentions:</b>",
        styles["RptBody"]
    ))
    risks = [
        "<b>Regulatory whiplash:</b> A single SEC action on a tokenized-Treasury issuer can freeze redemptions across the wrapper layer.",
        "<b>Oracle dependency:</b> RWA pricing depends on Chainlink / Pyth / API3 feeds. A stale oracle = a liquidation cascade.",
        "<b>\"Real yield\" myth:</b> Many \"RWA yield\" products are partially subsidized by protocol token emissions. Strip out the incentive layer and the real yield is often 150-300 bps lower.",
    ]
    for r in risks:
        elems.append(Paragraph(r, styles["RptBullet"], bulletText="•"))
    elems.append(PageBreak())
    return elems


def depin_chapter(styles):
    elems = []
    elems.append(Paragraph("3. DePIN - Decentralized Physical Infrastructure", styles["ChapterHead"]))

    elems.append(Paragraph("3.1 Industry Drivers", styles["SectionHead"]))
    elems.append(Paragraph(
        "Messari's framing is that 2026 is the year crypto transitions \"from speculation to system-level integration.\" DePIN is the most literal embodiment: networks where the supply side is physical hardware - GPUs, hotspots, sensors, storage drives - and the demand side is real-world compute or bandwidth customers.",
        styles["RptBody"]
    ))
    elems.append(Paragraph(
        "The reason this matters now: <b>the AI compute shortage is real, and it is not abating.</b> Render and Akash have absorbed spillover demand from AWS/GCP/Azure capacity constraints, particularly for inference workloads.",
        styles["RptBody"]
    ))

    elems.append(Paragraph("3.2 Top 10 DePIN Networks Compared", styles["SectionHead"]))
    depin_data = [
        ["Network", "Resource", "Network Size", "Revenue Model", "Demand Driver"],
        ["Render", "GPU rendering", "100k+ nodes", "Per-frame fees", "3D/VFX/AI"],
        ["Akash", "Cloud compute", "15k+ providers", "Per-second compute", "AI inference"],
        ["Filecoin", "Storage", "4,000+ PiB", "Storage deals", "AI datasets"],
        ["Helium", "Wireless (LoRa/5G)", "1M+ hotspots", "Coverage proofs", "IoT/Mobile"],
        ["io.net", "GPU clusters", "200k+ GPUs", "Compute marketplace", "AI/ML training"],
        ["Aethir", "GPUaaS", "60k+ containers", "Container rental", "Gaming/AI"],
        ["Livepeer", "Video transcode", "100k+ nodes", "Per-stream fees", "Video infra"],
        ["Arweave", "Perm storage", "Decentralized", "Per-upload fees", "Archival/NFTs"],
        ["Theta", "Video delivery", "100k+ nodes", "Edge compute", "Streaming"],
        ["Storj", "Object storage", "80k+ nodes", "Per-GB stored", "Backup/CDN"],
    ]
    t = Table(depin_data, colWidths=[2.6 * cm, 3.0 * cm, 3.0 * cm, 3.4 * cm, 3.5 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0a0e27")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 0.4 * cm))

    elems.append(Paragraph("3.3 Hidden Economics & Risks", styles["SectionHead"]))
    elems.append(Paragraph(
        "Most DePIN networks look cheap on a token-vs-revenue basis. The trap is that <b>token issuance subsidizes most of the supply-side revenue</b>. Once issuance halves, the supply side exits. The protocols that survive H2 2026 will be the ones with real demand-side revenue - and on this metric, Akash and Render are the strongest; Helium and Filecoin are still finding their footing.",
        styles["RptBody"]
    ))
    risks = [
        "<b>Demand-side concentration:</b> A single AI lab pulling GPUs off Akash can crash utilization overnight.",
        "<b>Tokenomics cliff:</b> Many DePIN tokens are still inflation-funded; the \"real revenue\" multiple is a fiction.",
        "<b>Hardware obsolescence:</b> A GPU bought today is obsolete in 18 months. The token may not cover depreciation.",
    ]
    for r in risks:
        elems.append(Paragraph(r, styles["RptBullet"], bulletText="•"))
    elems.append(PageBreak())
    return elems


def ai_agent_chapter(styles):
    elems = []
    elems.append(Paragraph("4. The Agentic Web - AI Agents On-Chain", styles["ChapterHead"]))

    elems.append(Paragraph("4.1 Why AI Agents Are the Most Important H2 2026 Narrative", styles["SectionHead"]))
    elems.append(Paragraph(
        "Two data points frame this:",
        styles["RptBody"]
    ))
    bullets = [
        "<b>GitHub Trending is dominated by Agent frameworks.</b> In June 2026, obra/superpowers added 19,921 stars in a single week and surpassed 102,000 total. CopilotKit and open-notebook rotated on the daily list. This is not a hype cycle - this is developers voting with their commits.",
        "<b>Messari predicts on-chain AI Agent payment flows will reach 25% of total on-chain value by year-end.</b> Even if this is off by 2x, the directional signal is unambiguous.",
    ]
    for b in bullets:
        elems.append(Paragraph(b, styles["RptBullet"], bulletText="•"))
    elems.append(Paragraph(
        "The synthesis: <b>AI Agents are becoming first-class citizens of the on-chain economy.</b> They execute trades, route payments, vote in governance, and split content revenue. The infrastructure layer (Bittensor, Ritual, Allora) and the application layer (autonomous treasuries, AI-managed portfolios, agentic commerce) are both being built in parallel.",
        styles["RptBody"]
    ))

    elems.append(Paragraph("4.2 Three Sub-Layers", styles["SectionHead"]))
    elems.append(Paragraph("<b>Infrastructure Layer (AI Compute + Models On-Chain)</b>", styles["RptBody"]))
    infra_data = [
        ["Protocol", "Role", "Market Cap", "Notes"],
        ["Bittensor (TAO)", "Training/inference marketplace", "$4B+", "Bitcoin of AI"],
        ["Ritual", "Model hosting + inference", "TBA", "Strong narrative"],
        ["Allora", "Self-improving ML", "$200M+", "Technically credible"],
        ["Akash / Render", "Compute supply", "See DePIN", "Cross-listed"],
    ]
    t = Table(infra_data, colWidths=[3.5 * cm, 4.0 * cm, 2.8 * cm, 5.2 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0a0e27")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 0.3 * cm))

    elems.append(Paragraph("<b>Framework Layer (Off-Chain, Open Source)</b>", styles["RptBody"]))
    framework_data = [
        ["Project", "Language", "Star Velocity", "Differentiation"],
        ["obra/superpowers", "Shell", "+19,921/wk", "Most-trending; modular"],
        ["CopilotKit", "TS/JS", "+613/day", "In-app agent integration"],
        ["open-notebook", "Python", "+783/day", "Research-style agents"],
        ["AutoGen", "Python", "Steady", "Multi-agent orchestration"],
        ["CrewAI", "Python", "Steady", "Role-based agent teams"],
        ["LangGraph", "Python", "Steady", "Graph-based workflows"],
    ]
    t = Table(framework_data, colWidths=[3.5 * cm, 2.2 * cm, 3.0 * cm, 6.8 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0a0e27")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 0.3 * cm))

    elems.append(Paragraph("<b>Application Layer (On-Chain Agents)</b>", styles["RptBody"]))
    elems.append(Paragraph(
        "This is the least developed - and therefore the highest opportunity - layer. Examples include autonomous treasuries (MakerDAO's AI-assisted vault management), agentic commerce (agents that negotiate and pay for services), AI-curated content feeds (Mirror / Paragraph + recommendation agents), and on-chain governance delegates.",
        styles["RptBody"]
    ))

    elems.append(Paragraph("4.3 Participation Entry Points & Risks", styles["SectionHead"]))
    bullets = [
        "<b>Open-source a vertical agent framework:</b> The market is fragmented. A focused framework (e.g., agents for crypto content research) can capture GitHub stars and Sponsors within 60-90 days.",
        "<b>Sell AI Agent development consulting:</b> Demand is severe. Fiverr/Upwork postings for \"build me a CrewAI / AutoGen agent\" are rising 30%+ month-over-month.",
        "<b>Build the analytics layer for Agent payments:</b> On-chain agent transaction tracking is nascent. A Dune-style dashboard for \"AI Agent payment flows by protocol\" is a defensible niche.",
        "<b>Write the canonical \"State of the Agentic Web\" report:</b> Quarterly, with on-chain data + GitHub activity + funding rounds. This is a paid-subscription product waiting to exist.",
    ]
    for b in bullets:
        elems.append(Paragraph(b, styles["RptBullet"], bulletText="•"))
    elems.append(Paragraph(
        "<b>Risks nobody mentions:</b> Framework fatigue (number has tripled in 12 months, most will be abandoned); on-chain AI inference is still expensive (most agents route off-chain); an autonomous agent executing financial transactions may trigger money-transmitter licensing in multiple jurisdictions.",
        styles["RptBody"]
    ))
    elems.append(PageBreak())
    return elems


def intersection_chapter(styles):
    elems = []
    elems.append(Paragraph("5. The Intersection: Where Breakout Opportunities Live", styles["ChapterHead"]))
    elems.append(Paragraph(
        "The truly interesting H2 2026 opportunities sit at the intersections of the three mainlines:",
        styles["RptBody"]
    ))

    inter_data = [
        ["Intersection", "Example Opportunity"],
        ["RWA + DePIN", "Tokenized revenue streams from DePIN hardware operators (e.g., a Render node's monthly render fees securitized as an RWA)."],
        ["RWA + Agents", "Autonomous treasuries that route between T-bills, private credit, and stablecoins based on macro signals."],
        ["DePIN + Agents", "AI Agents that bid for GPU capacity on Akash / Render autonomously, optimizing for cost and latency."],
        ["All three", "A protocol that tokenizes AI compute capacity as an RWA, traded on a decentralized exchange, with agents doing market making."],
    ]
    t = Table(inter_data, colWidths=[3.5 * cm, 12.0 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0a0e27")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 0.4 * cm))
    elems.append(Paragraph(
        "These intersections are where the next cohort of breakout protocols will emerge - and where the most valuable research, content, and consulting opportunities are today.",
        styles["RptBody"]
    ))
    elems.append(PageBreak())
    return elems


def playbook_chapter(styles):
    elems = []
    elems.append(Paragraph("6. Independent Operator Playbook", styles["ChapterHead"]))
    elems.append(Paragraph(
        "For solo creators, freelancers, and small AI companies, the playbook is:",
        styles["RptBody"]
    ))
    steps = [
        "<b>Pick one mainline as your \"beat.\"</b> Trying to cover all three at depth is impossible without a team. AutoCorp is choosing AI Agents as primary, with RWA and DePIN as adjacent coverage.",
        "<b>Build a publication layer on Mirror.xyz + Paragraph.</b> Web3-native, ETH-tippable, no Stripe dependency. (Critical for operators without company formation.)",
        "<b>Productize one piece of your research as a paid artifact on Gumroad.</b> Even a $9 PDF creates a price anchor and a customer list.",
        "<b>Open-source one tool.</b> GitHub Sponsors + credibility + inbound consulting leads.",
        "<b>Take 2-3 high-margin consulting gigs on Fiverr / Upwork.</b> Crypto market analysis and AI Agent architecture are the two highest-margin categories right now.",
        "<b>Track the intersections.</b> The breakout opportunity of H2 2026 is unlikely to be \"another RWA lending protocol.\" It is far more likely to be at the intersection of two of these mainlines.",
    ]
    for s in steps:
        elems.append(Paragraph(s, styles["RptBullet"], bulletText="•"))
    elems.append(PageBreak())
    return elems


def risk_chapter(styles):
    elems = []
    elems.append(Paragraph("7. Risk Analysis Across All Three Mainlines", styles["ChapterHead"]))
    risk_data = [
        ["Risk Type", "Description", "Severity"],
        ["Macro risk", "A risk-off event (rate hike surprise, geopolitical shock) compresses valuations across RWA, DePIN, and AI Agent tokens simultaneously.", "High"],
        ["Regulatory risk", "Tokenized securities, decentralized infrastructure, and autonomous financial agents each face distinct and unresolved regulatory frameworks.", "High"],
        ["Narrative decay", "Any of these three could lose narrative dominance in 90 days. Monitor GitHub star velocity, on-chain TVL, and Google Trends as leading indicators.", "Medium"],
        ["Operator risk", "For independent operators, the dominant risk is spreading too thin. The compounding returns come from depth in one mainline, not breadth across all three.", "High"],
        ["Oracle risk", "RWA pricing depends on Chainlink/Pyth/API3 feeds. A stale oracle can trigger a liquidation cascade.", "Medium"],
        ["Tokenomics cliff", "Many DePIN tokens are inflation-funded; the \"real revenue\" multiple is a fiction.", "High"],
        ["Framework fatigue", "Number of AI Agent frameworks has tripled in 12 months. Most will be abandoned.", "Medium"],
    ]
    t = Table(risk_data, colWidths=[3.0 * cm, 11.5 * cm, 1.8 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0a0e27")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elems.append(t)
    elems.append(PageBreak())
    return elems


def catalyst_calendar(styles):
    elems = []
    elems.append(Paragraph("Appendix A: 30-Day Catalyst Calendar", styles["ChapterHead"]))
    cal_data = [
        ["Date", "Event", "Impact"],
        ["Jul 10, 2026", "Fed FOMC minutes release", "RWA yields"],
        ["Jul 15, 2026", "Ondo Finance quarterly report", "RWA"],
        ["Jul 20, 2026", "Render network upgrade v3", "DePIN"],
        ["Jul 25, 2026", "Akash new GPU provider onboarding", "DePIN"],
        ["Aug 01, 2026", "CrewAI v0.40 release", "AI Agent"],
        ["Aug 05, 2026", "Bittensor subnet 23 launch", "AI Agent"],
        ["Aug 10, 2026", "SEC tokenization framework comment period ends", "RWA"],
        ["Aug 15, 2026", "MakerDAO endgame phase 2 vote", "RWA + Stable"],
        ["Aug 20, 2026", "Filecoin FIL+ recalculation", "DePIN"],
        ["Aug 25, 2026", "obra/superpowers v2 release", "AI Agent"],
    ]
    t = Table(cal_data, colWidths=[3.0 * cm, 9.0 * cm, 4.3 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0a0e27")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
    ]))
    elems.append(t)
    elems.append(PageBreak())
    return elems


def glossary(styles):
    elems = []
    elems.append(Paragraph("Appendix B: Glossary", styles["ChapterHead"]))
    glossary_data = [
        ["Term", "Definition"],
        ["RWA", "Real World Assets - off-chain assets (Treasuries, real estate, private credit) tokenized on-chain."],
        ["DePIN", "Decentralized Physical Infrastructure Networks - networks where supply side is physical hardware."],
        ["AI Agent", "Autonomous software that executes tasks, makes decisions, and may transact on-chain without human in the loop."],
        ["Agentic Web", "The emerging ecosystem of on-chain AI Agents that transact, vote, and route payments autonomously."],
        ["TVL", "Total Value Locked - the USD value of assets deposited in a protocol."],
        ["APY", "Annual Percentage Yield - the annualized return including compounding."],
        ["Tokenomics", "The economic design of a token: issuance schedule, distribution, utility, and burn mechanisms."],
        ["Oracle", "A service that feeds off-chain data (prices, rates, events) into on-chain smart contracts."],
        ["MEV", "Maximal Extractable Value - profit that can be extracted by reordering, including, or excluding transactions."],
        ["Restaking", "Restaking staked ETH (e.g., stETH) to secure additional protocols (e.g., EigenLayer)."],
    ]
    t = Table(glossary_data, colWidths=[3.0 * cm, 13.3 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0a0e27")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elems.append(t)
    elems.append(PageBreak())
    return elems


def methodology(styles):
    elems = []
    elems.append(Paragraph("Appendix C: Data Sources & Methodology", styles["ChapterHead"]))
    elems.append(Paragraph(
        "This report aggregates data from the following sources, accessed between June 25 and July 4, 2026:",
        styles["RptBody"]
    ))
    sources = [
        "<b>DefiLlama</b> - TVL, fee revenue, and yield data across all chains",
        "<b>Dune Analytics</b> - Custom dashboards for RWA collateral composition and DePIN revenue",
        "<b>Token Terminal</b> - Protocol-level revenue and multiple analysis",
        "<b>Messari</b> - 2026 thesis reports and protocol research",
        "<b>GitHub Trending</b> - Repository star velocity and contributor counts",
        "<b>CoinGecko</b> - Token prices and market caps",
        "<b>Official protocol dashboards</b> - On-chain metrics directly from Ondo, Centrifuge, MakerDAO, Render, Akash",
        "<b>SEC EDGAR</b> - Tokenized Treasury issuer filings",
    ]
    for s in sources:
        elems.append(Paragraph(s, styles["RptBullet"], bulletText="•"))
    elems.append(Paragraph(
        "<b>Methodology</b>: Yield figures are snapshot as of June 29, 2026, 16:23 UTC. \"Real yield\" is computed by subtracting protocol token emissions from headline APY where applicable. TVL figures use DefiLlama's methodology (excluding double-counted stETH/wstETH).",
        styles["RptBody"]
    ))
    elems.append(PageBreak())
    return elems


def disclaimer(styles):
    elems = []
    elems.append(Paragraph("Appendix D: Disclaimer", styles["ChapterHead"]))
    elems.append(Paragraph(
        "This report is for informational purposes only and does not constitute investment advice, financial advice, trading advice, or any other sort of advice. Nothing in this report should be construed as a recommendation to buy, sell, or hold any token, security, or other financial instrument.",
        styles["Disclaimer"]
    ))
    elems.append(Paragraph(
        "AutoCorp is an independent AI research desk. We do not hold or promote tokens covered in this report unless explicitly disclosed. We may hold positions in protocols mentioned; positions are disclosed in our public treasury wallet at ${ETH_TIPPING_ADDRESS}.",
        styles["Disclaimer"]
    ))
    elems.append(Paragraph(
        "Past performance is not indicative of future results. Crypto assets are volatile and can result in total loss of principal. Always conduct your own due diligence and consult with a licensed financial advisor before making any investment decisions.",
        styles["Disclaimer"]
    ))
    elems.append(Paragraph(
        "© 2026 AutoCorp Research Desk. All rights reserved. No part of this report may be reproduced without attribution.",
        styles["Disclaimer"]
    ))
    return elems


def footer(canvas_obj, doc):
    """Page footer with page number."""
    canvas_obj.saveState()
    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.setFillColor(colors.HexColor("#666666"))
    canvas_obj.drawCentredString(A4[0] / 2, 1.5 * cm, f"AutoCorp Research Desk  |  H2 2026 Crypto Report  |  Page {doc.page}")
    canvas_obj.restoreState()


def main():
    print(f"Generating PDF: {OUTPUT_PDF}")
    styles = build_styles()

    doc = SimpleDocTemplate(
        str(OUTPUT_PDF),
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title="The Three Crypto Mainlines of H2 2026",
        author="AutoCorp Research Desk",
        subject="RWA + DePIN + AI Agent Deep Analysis",
    )

    story = []
    story.extend(cover_page(styles))
    story.extend(toc_page(styles))
    story.extend(exec_summary(styles))
    story.extend(rwa_chapter(styles))
    story.extend(depin_chapter(styles))
    story.extend(ai_agent_chapter(styles))
    story.extend(intersection_chapter(styles))
    story.extend(playbook_chapter(styles))
    story.extend(risk_chapter(styles))
    story.extend(catalyst_calendar(styles))
    story.extend(glossary(styles))
    story.extend(methodology(styles))
    story.extend(disclaimer(styles))

    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    print(f"OK: {OUTPUT_PDF}")
    print(f"   Size: {OUTPUT_PDF.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    main()
